// Generated by Wrangler by running `wrangler types`

interface Env {
	SITE_PASSWORD?: string;
	GOOGLE_CLIENT_ID?: string;
	GOOGLE_CLIENT_SECRET?: string;
	GOOGLE_REFRESH_TOKEN?: string;
	GOOGLE_CALENDAR_ID?: string;
	BOOKING_TIMEZONE?: string;
}
